version: '2.1'

services:
  dante:
    build: dante
    hostname: dante
    container_name: dante
    volumes:
      - ./etc:/etc
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"
    restart: unless-stopped
    environment:
      PORT: 8081
      EXTERNAL_HOSTNAME: ""
